const mongo=require('mongoose');
const schema=mongo.Schema;

var Orderschema=mongo.Schema({
      user : {
            // it refers to the type of the column of object
            type:schema.Types.ObjectId,
            // I determine the object that the type refers to
            ref:'Users',
            required:true
      },
      cart : {
            type:Object,
            required:true
      },
      name : {
            type:String,
            required:true
      },
      address : {
            type:String,
            required:true
      },
      totalPrice : {
            type:Number,
            required:true
      },
      
      // it comes from the payment's reply but now I am gonna generated by myself because the payment stripe doesn't work
      paymentId : {
            type : String,
            required : true
      },

      // To delete the order after a period

});

module.exports=mongo.model('Orders',Orderschema);